groovy -cp $GEMFIRE/lib/server-dependencies.jar ClearRegions.groovy -l localhost -p 10334 ChannelRates,ChannelRatesByDestinationXref,ChannelRatesByPropertyIdXref,ChannelRatesByNoDestinationAndNoPropertyIdXref,ChannelRatesByCheckinEndDateXref,ChannelRatesByCheckinStartDateXref,ChannelRatesByEffectiveEndDateXref,ChannelRatesByEffectiveStartDateXref,ChannelRatesByMaxLosXref,ChannelRatesByMinLosXref
 

#Promotions,PromotionsByDestinationXref,PromotionsByPropertyIdXref

#ChannelRates,ChannelRatesByDestinationXref,ChannelRatesByPropertyIdXref,ChannelRatesByNoDestinationAndNoPropertyIdXref

#Promotions,PromotionsByDestinationXref,PromotionsByPropertyIdXref

